### ISSUE TITLE
Monsters arent spawning, there is no teleporter and no spawnables [multiplayer] 

### ISSUE THREAD

**Issue by JammingEnd** [FocusedFault/EntropyStages#1]
We are the first to play your mod, but on the corrupted titanic plains stage nothing basically happened. we played with 4 players

**Comment by Redund0** [comment]
I second this bug. This happened twice. Also there are only 2 Lunar seers. Played solo.
![image](https://github.com/FocusedFault/EntropyStages/assets/112259739/6223e4ec-307d-424b-8194-de5431f46f29)

**Comment by Nuxlar** [comment]
was this before or after the 0.9.1 update, everything should be working now

**Comment by VitrolicWither** [comment]
Enemies and interactable are spawning now but the lunar seers are messed up for me. I'm using another mod called WolfoQualityOfLife that adds a third seer and I think they are conflicting. could you add compatibly between the two or just a config to turn the seer off?

**Comment by Nuxlar** [comment]
latest removes the seer
