### ISSUE TITLE
Softlocks in multiplayer

### ISSUE THREAD

**Issue by BubbleTanks** [FocusedFault/EntropyStages#3]
I don't really know why, but in multiplayer, we consistently have players not spawning in, or sometimes none of us spawn in at all, when loading into the simulacrum maps.

**Comment by RotKingJoey** [comment]
Can confirm this is also occurring in my testing, only the host seems to spawn in when in a multiplayer session.

**Comment by Nuxlar** [comment]
interesting, I'll look into it

**Comment by gu0dan** [comment]
I'm having the same issue! only the host is able to spawn. additionally, non-host players, that fall off the stage, don't re-spawn on the surface, but continue falling endlessly.

**Comment by Nuxlar** [comment]
a temporary fix for now, add debugtoolkit to your modpack and have them try the respawn console command, that might work until I get it working

**Comment by Nuxlar** [comment]
fixed main error of players not spawning in, still need to fix consistency stuff but it shouldn't softlock anymore
